# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TRACSMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TRACSMobile
  pod 'Firebase/Core'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-wkwebview', :path => '../node_modules/react-native-wkwebview-reborn'

  target 'TRACSMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
